### ISSUE TITLE
Not displaying duration time on each test case

### ISSUE THREAD

**Issue by luuizeduardo** [reportportal/agent-js-jest#17] opened 2019-06-11 13:42 UTC
Even though the launch shows up the execution time duration for the entire test suit, the individual test cases are not displaying the same information instead are just "0s". Find below the printscreen:

![Screen Shot 2019-06-11 at 10 19 04](https://user-images.githubusercontent.com/36016665/59276271-6314b400-8c34-11e9-9202-610db3832c53.png)

This items are defined as `describes` within my test suit. Inside of each test case there are many checks and those don't display the duration time eather.

**Comment by AmsterGet** [comment] 2020-08-05 23:34
It looks like the problem is that the test execution time is too short. Thus, if the duration of the test item is less than 2 characters after the decimal point, it will display as 0.
I'll close this issue.
Feel free to reopen it if you have any other questions related to thistopic.

**Closed by AmsterGet** 2020-08-05 23:34 UTC
Labels: bug
