### ISSUE TITLE
nested describe blocks are not visible in report

### ISSUE THREAD

**Issue by amartanwar42** [reportportal/agent-js-jest#56] opened 2020-07-16 14:14 UTC
Where there are multiple nested blocks all test appears under parent describe block in reports.

**Comment by evjlobanova** [comment] 2020-07-17 08:22
@amartanwar42 we need information about:
- agent version 
- example project with a mistake so that we can reproduce this bug
- any other details regarding issue

**Comment by evjlobanova** [comment] 2020-07-17 08:22
@KatsiarynaTatarynovich could you please check this issue and label it

**Comment by techblueprint** [comment] 2020-07-20 06:27
Please find below information:

Agent version: Issue is replicated on both **5.0.0** and **5.0.1**
Example project: attached herewith

Additional information - the issue happens when a user has either nested describe or multiple describe in a test file.
[example-jest.zip](https://github.com/reportportal/agent-js-jest/files/4945856/example-jest.zip)

**Comment by AmsterGet** [comment] 2020-08-05 23:15
There seems to be something missing in the agent itself! Thanks for finding.
We will investigate this issue deeper and plan the implementation.

**Comment by AmsterGet** [comment] 2020-08-06 10:12
Task created!

**Comment by AmsterGet** [comment] 2021-04-16 07:44
Will be released in [5.0.3](https://github.com/reportportal/agent-js-jest/pull/69).

**Closed by AmsterGet** 2021-04-16 07:44 UTC
Labels: bug
