### ISSUE TITLE
Nested Descibe blocks are not coming up and all test shows up in parent describe

### ISSUE THREAD

**Issue by myautomationeng** [reportportal/agent-js-jest#62] opened 2020-12-08 11:28 UTC
I have included actual and expected result for sample test

Inner Describe gets left out and drill down missed in Ui

-----Expected
 GET Test Suite
	Get the entity used for comparison using google id
	Test	
	gets a response0s
	Test	
	has a defined settings.displayLanguage property0s
	Test	
	has a defined lastLoginDate property0s
	Test	
	has a defined isMailboxSetup property0s
	Test	
	properly combines the family name and given name into the full name0s
	Test	
	has a defined messagesTotal property0s

 Get using primary email
	Test	
	gets a response0s
	Test	
	returns a 200 status code0s
	Test	
	returns the proper entity data0s
	Test	
	gets a response0s
	Test	
	gets a response for each alias with the proper body0s
	Test	
	returns a 200 status code0s
	Test	
	returns the proper entity data0s

-----Actual

Expected
 GET Test Suite
	
	Test	
	gets a response0s
	Test	
	has a defined settings.displayLanguage property0s
	Test	
	has a defined lastLoginDate property0s
	Test	
	has a defined isMailboxSetup property0s
	Test	
	properly combines the family name and given name into the full name0s
	Test	
	has a defined messagesTotal property0s

	Test	
	gets a response0s
	Test	
	returns a 200 status code0s
	Test	
	returns the proper entity data0s
	Test	
	gets a response0s
	Test	
	gets a response for each alias with the proper body0s
	Test	
	returns a 200 status code0s
	Test	
	returns the proper entity data0s

---------------Sample Code

const supertest = require('supertest');
const _ = require('lodash');
const { getHardcodeProps } = require('../../config/jestTests');
let server;

beforeAll(() => {
  jest.setTimeout(15000);
  server = require('../server');
});
afterAll(() => {
  server.close();
});

const { basePath, id, primaryEmail } = getHardcodeProps;

describe(`GET Test Suite`, async () => {
  let sanityObject;
  describe('Get the entity used for comparison using google id', async () => {
    let res;
    it(`gets a response`, async () => {
      res = await supertest(server).get(`${basePath}/${id}`);
      expect(res.status).toBe(200);
      expect(res.body).toBeDefined();
      sanityObject = { ...res.body };
    });

    it(`has a defined lastLoginDate property`, async () => {
      expect(sanityObject.lastLoginDate).toBeDefined();
    });

    it(`has a defined settings.displayLanguage property`, async () => {
      expect(sanityObject.settings.displayLanguage).toBeDefined();
    });

    it(`has a defined isMailboxSetup property`, async () => {
      expect(sanityObject.isMailboxSetup).toBeDefined();
    });

    it(`properly combines the family name and given name into the full name`, async () => {
      const fullName = _.find(sanityObject.serviceCharacteristic, {
        name: 'fullName',
      });
      const givenName = _.find(sanityObject.serviceCharacteristic, {
        name: 'givenName',
      });
      const familyName = _.find(sanityObject.serviceCharacteristic, {
        name: 'familyName',
      });
      expect(fullName).toBeDefined();
      expect(givenName).toBeDefined();
      expect(familyName).toBeDefined();
      expect(fullName.value).toBe(`${givenName.value} ${familyName.value}`);
    });

    it(`has a defined messagesTotal property`, async () => {
      expect(sanityObject.messagesTotal).toBeDefined();
    });
  });

  describe('Get using primary email', async () => {
    let res;

    it(`gets a response`, async () => {
      res = await supertest(server).get(`${basePath}/${primaryEmail}`);
      expect(res.body).toBeDefined();
    });

    it(`returns a 200 status code`, async () => {
      expect(res.status).toBe(200);
    });

    it(`returns the proper entity data`, async () => {
      expect(res.body).toEqual(sanityObject);
    });
  });

  describe('Get using the aliases', async () => {
    let res;

    it(`gets a response for each alias with the proper body`, async () => {
      for (const alias of sanityObject.aliases) {
        res = await supertest(server).get(`${basePath}/${alias}`);
        expect(res.body).toBeDefined();
        expect(res.status).toBe(200);

        //Delete the settings property, as wont be able to retrieve the gmail settings using an alias (must be primary key)
        const getBodyStripped = _.cloneDeep(res.body);
        delete getBodyStripped.settings;
        delete getBodyStripped.messagesTotal;
        const sanityObjectStripped = _.cloneDeep(sanityObject);
        delete sanityObjectStripped.settings;
        delete sanityObjectStripped.messagesTotal;

        expect(getBodyStripped).toMatchObject(sanityObjectStripped);
      }
    });
  });

  describe('Gets only the aliases if passed in fields query parameter', async () => {
    let res;

    it(`gets a response`, async () => {
      res = await supertest(server).get(`${basePath}/${id}?fields=aliases`);
      expect(res.body).toBeDefined();
    });

    it(`returns a 200 status code`, async () => {
      expect(res.status).toBe(200);
    });

    it(`returns the proper entity data`, async () => {
      expect(res.body).toEqual({ aliases: sanityObject.aliases });
    });
  });

  describe('Gets only the primaryEmail if passed in fields query parameter', async () => {
    let res;

    it(`gets a response`, async () => {
      res = await supertest(server).get(
        `${basePath}/${id}?fields=primaryEmail`
      );
      expect(res.body).toBeDefined();
    });

    it(`returns a 200 status code`, async () => {
      expect(res.status).toBe(200);
    });

    it(`returns the proper entity data`, async () => {
      expect(res.body).toEqual({ primaryEmail: sanityObject.primaryEmail });
    });
  });

  describe('Gets both the aliases and the primaryEmail if passed in fields query parameter', async () => {
    let res;

    it(`gets a response`, async () => {
      res = await supertest(server).get(
        `${basePath}/${id}?fields=primaryEmail,aliases`
      );
      expect(res.body).toBeDefined();
    });

    it(`returns a 200 status code`, async () => {
      expect(res.status).toBe(200);
    });

    it(`returns the proper entity data`, async () => {
      expect(res.body).toEqual({
        primaryEmail: sanityObject.primaryEmail,
        aliases: sanityObject.aliases,
      });
    });
  });
});

Result in Report AI will be 

GET Test Suite

**Comment by AmsterGet** [comment] 2021-03-18 11:42
Closed as duplicate of https://github.com/reportportal/agent-js-jest/issues/56

**Closed by AmsterGet** 2021-03-18 11:42 UTC
