### ISSUE TITLE
Getting 400 error

### ISSUE THREAD

**Issue by JustinChetty** [reportportal/agent-js-jest#82] opened 2021-07-28 07:31 UTC
Getting below error when using package wit jest

Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at C:\Sanlam Projects\Automation\node_modules\@reportportal\client-javascript\lib\rest.js:36:23

**Comment by AmsterGet** [comment] 2021-08-30 13:11
Hello @JustinChetty !
At what stage did you get this error?
It seems that the agent did not provide some data to the client (`name`) and this resulted in an error.

**Comment by Wraithraiser** [comment] 2021-11-24 11:23
Hello @JustinChetty, I had the same error and it's probably because a test file is missing `describe()` 🤔 
It's possible to reproduce the bug using this example:

```
const addition = (a, b) => a + b;

describe('addition', () => {
  it('should return 5', () => {
    const result = addition(2, 3);
    expect(result).toBe(5);
  });
});

it('addition should return 5', () => {
  const result = addition(2, 3);
  expect(result).toBe(5);
});
```
The test without `describe` wrapping cause the bug.

**Comment by oranje322** [comment] 2022-04-04 15:56
The task has been created.
Will be fixed in next version.

**Closed** 2022-05-30 14:27 UTC
Labels: bug
