### ISSUE TITLE
Log console.log() messages in report portal.

### ISSUE THREAD

**Issue by chaitanya-uc** [reportportal/agent-js-jest#85] opened 2021-11-10 07:01 UTC
Is there any way to log the console log messages in the report portal? It will be very helpful for debugging purposes.

**Comment by chivekrodis** [comment] 2022-02-22 08:32
Hello @chaitanya-uc ,
Unfortunately, agent have no ability report logs to the test. However it looks like we have the ability to send all jest logs to launch. Do you think it will be useful?

**Comment by AmsterGet** [comment] 2022-02-22 12:34
Duplicate of https://github.com/reportportal/agent-js-jest/issues/89
You can follow the thread under this issue.

**Closed by AmsterGet** 2022-02-22 12:34 UTC
